# Makefile for compactflash.device
# Build using vasm/ASMPro (assembler) and vbcc (C compiler)
#
# Usage: make [options] [target]
#   help - show detailed usage output

# Driver Version (update these for new releases)
VERSION_MAJOR = 1
VERSION_MINOR = 38
VERSION_SUFFIX = -dev
DATE = 23.01.2026
DATE_SHORT = 01/2026

# Tool-specific versions
CFINFO_VERSION = 1.37
CFINFO_DATE = 11.01.2026

PCMCIASPEED_VERSION = 1.36
PCMCIASPEED_DATE = 02.01.2026

PCMCIACHECK_VERSION = 1.38
PCMCIACHECK_DATE = 22.01.2026

# Derived version
VERSION = $(VERSION_MAJOR).$(VERSION_MINOR)$(VERSION_SUFFIX)
VERSION_NODOT = $(VERSION_MAJOR)$(VERSION_MINOR)

# Version string for assembler# Generate version include file for assembler
VERSION_INC = src/version.i

# Verbose mode (V=1 for verbose output)
ifeq ($(V),1)
  Q =
  DEFINITIONS =
else
  Q = @
  DEFINITIONS = -quiet
endif

# FASTPIO: Gayle timing optimization
# Maps CF card PIO modes to optimal Gayle PCMCIA timing
# Default" disabled (experimental, set FASTPIO=1 to enable)
TEXT=""
FASTPIO ?= 0
ifeq ($(FASTPIO),1)
  TEXT=", +gayletiming"
  DEFINITIONS += -DFASTPIO=$(FASTPIO)
else
  TEXT=", -gayletiming"
endif

# COPYBURST: Enable MOVEM burst transfers for memory operations
# Uses MOVEM.L for 8-byte burst reads/writes
# Default" disabled (experimental, set COPYBURST=1 to enable)
COPYBURST ?= 0
ifeq ($(COPYBURST),1)
  TEXT:="$(TEXT), +copyburst"
  DEFINITIONS += -DCOPYBURST=$(COPYBURST)
else
  TEXT:="$(TEXT), -copyburst"
endif

# Tools (override these for different installations)
VASM_HOME = /opt/vbcc
VBCC_HOME = /opt/vbcc
VASM = $(VASM_HOME)/bin/vasmm68k_mot
VBCC = $(VBCC_HOME)/bin/vc
LHA = lha

# Flags
VASMFLAGS = -Fhunkexe -m68020 -nosym $(DEFINITIONS)
VBCCFLAGS = +aos68k -O2 -c99 -INDK/Include_H

# Directories
SRCDIR = src
OUTDIR = devs

# Files: Driver
SOURCE = $(SRCDIR)/cfd.s
TARGET_FULL = $(OUTDIR)/compactflash.device
TARGET_SMALL = $(OUTDIR)/compactflash.device.small

# Files: Tools
SOURCE_CFINFO = $(SRCDIR)/cfinfo.c
TARGET_CFINFO = c/CFInfo
SOURCE_PCMCIASPEED = $(SRCDIR)/pcmciaspeed.c
TARGET_PCMCIASPEED = c/pcmciaspeed
SOURCE_PCMCIACHECK = $(SRCDIR)/pcmciacheck.c
TARGET_PCMCIACHECK = c/pcmciacheck

# Files: Release
RELEASE_NAME = cfd$(VERSION_NODOT)
ARCHIVE_NAME = $(RELEASE_NAME).lha
README_NAME = $(RELEASE_NAME).readme
README_TEMPLATE = cfd.readme.in

# ============================================================
# Build targets
# ============================================================

# Default target - build both versions and tools
all: version-readme $(TARGET_FULL) $(TARGET_SMALL) $(TARGET_CFINFO) $(TARGET_PCMCIASPEED) $(TARGET_PCMCIACHECK)

# Generate version include file (always check, only update if changed)
# Uses a stamp file to track the current version string
VERSION_STAMP = .version-stamp
.PHONY: FORCE
FORCE:

$(VERSION_STAMP): FORCE
	$(Q)echo "$(VERSION) $(DATE)" > $(VERSION_STAMP).tmp
	$(Q)if ! cmp -s $(VERSION_STAMP).tmp $(VERSION_STAMP) 2>/dev/null; then \
		mv $(VERSION_STAMP).tmp $(VERSION_STAMP); \
	else \
		rm -f $(VERSION_STAMP).tmp; \
	fi

$(VERSION_INC): $(VERSION_STAMP)
	$(Q)echo "  VERSION $(VERSION)"
	$(Q)echo "; Auto-generated by Makefile - do not edit" > $@
	$(Q)echo "FILE_VERSION	= $(VERSION_MAJOR)" >> $@
	$(Q)echo "FILE_REVISION	= $(VERSION_MINOR)" >> $@
	$(Q)echo "VERSION_STRING	macro" >> $@
	$(Q)echo "	dc.b	\"compactflash.device $(VERSION) ($(DATE))\"" >> $@
	$(Q)echo "	endm" >> $@

# Update version suffix in README.md (in-place)
# Updates the "What's New" section header: ### v1.36 or ### v1.36-dev
version-readme:
	$(Q)sed -i 's/^### v$(VERSION_MAJOR)\.$(VERSION_MINOR)[^[:space:]]*/### v$(VERSION)/' README.md
	$(Q)echo "  README  version updated to $(VERSION)"

# Full version (with serial debug capability)
$(TARGET_FULL): $(SOURCE) $(VERSION_INC)
	$(Q)echo "  VASM    $@ [full${TEXT}]"
	$(Q)$(VASM) $(VASMFLAGS) -DDEBUG=1 -o $@ $<
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

# Small version (no debug code/strings)
$(TARGET_SMALL): $(SOURCE) $(VERSION_INC)
	$(Q)echo "  VASM    $@ [small$(TEXT)]"
	$(Q)$(VASM) $(VASMFLAGS) -o $@ $<
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

# Build only full version
full: $(TARGET_FULL)

# Build only small version
small: $(TARGET_SMALL)

# Tools only target
tools: $(TARGET_CFINFO) $(TARGET_PCMCIASPEED) $(TARGET_PCMCIACHECK)

# Generate AmigaGuide documentation from Markdown
guides:
	$(Q)echo "  GUIDE   docs/*.guide"
	$(Q)tools/md2guide.py docs/CFInfo.md --version $(CFINFO_VERSION) --date $(CFINFO_DATE) --ver-title "CFInfo guide"
	$(Q)tools/md2guide.py docs/pcmciaspeed.md --version $(PCMCIASPEED_VERSION) --date $(PCMCIASPEED_DATE) --ver-title "pcmciaspeed guide"
	$(Q)tools/md2guide.py docs/pcmciacheck.md --version $(PCMCIACHECK_VERSION) --date $(PCMCIACHECK_DATE) --ver-title "pcmciacheck guide"
	$(Q)tools/md2guide.py README.md docs/cfd.guide --version $(VERSION) --date $(DATE) --title "compactflash.device" --ver-title "compactflash.device guide"

# CFInfo utility (requires vbcc)
$(TARGET_CFINFO): $(SOURCE_CFINFO)
	$(Q)mkdir -p c
	$(Q)echo "  VBCC    $(TARGET_CFINFO)"
	$(Q)VBCC=$(VBCC_HOME) PATH=$(VBCC_HOME)/bin:$$PATH $(VBCC) +aos68k -O2 -c99 -INDK/Include_H -DVERSION='"$(CFINFO_VERSION)"' -DDATE='"$(CFINFO_DATE)"' -o $(TARGET_CFINFO) $<
	$(Q)echo "          $$(stat -c%s $(TARGET_CFINFO)) bytes, md5:$$(md5sum $(TARGET_CFINFO) | cut -c1-8)"

# pcmciaspeed utility (requires vbcc)
$(TARGET_PCMCIASPEED): $(SOURCE_PCMCIASPEED)
	$(Q)mkdir -p c
	$(Q)echo "  VBCC    $(TARGET_PCMCIASPEED)"
	$(Q)VBCC=$(VBCC_HOME) PATH=$(VBCC_HOME)/bin:$$PATH $(VBCC) +aos68k -O2 -c99 -INDK/Include_H -DVERSION='"$(PCMCIASPEED_VERSION)"' -DDATE='"$(PCMCIASPEED_DATE)"' -o $(TARGET_PCMCIASPEED) $<
	$(Q)echo "          $$(stat -c%s $(TARGET_PCMCIASPEED)) bytes, md5:$$(md5sum $(TARGET_PCMCIASPEED) | cut -c1-8)"

# pcmciacheck utility (requires vbcc)
$(TARGET_PCMCIACHECK): $(SOURCE_PCMCIACHECK)
	$(Q)mkdir -p c
	$(Q)echo "  VBCC    $(TARGET_PCMCIACHECK)"
	$(Q)VBCC=$(VBCC_HOME) PATH=$(VBCC_HOME)/bin:$$PATH $(VBCC) +aos68k -O2 -c99 -INDK/Include_H -DVERSION='"$(PCMCIACHECK_VERSION)"' -DDATE='"$(PCMCIACHECK_DATE)"' -o $(TARGET_PCMCIACHECK) $<
	$(Q)echo "          $$(stat -c%s $(TARGET_PCMCIACHECK)) bytes, md5:$$(md5sum $(TARGET_PCMCIACHECK) | cut -c1-8)"

# ============================================================
# Release targets
# ============================================================

# Generate readme from template
$(README_NAME).info:
	@echo "Generating $(README_NAME).readme.info from template..."
	@cp cfd.readme.info.in $(README_NAME).info 2>/dev/null
	@echo "Generated: $@"

$(README_NAME): $(README_TEMPLATE) $(TARGET_FULL) $(TARGET_SMALL) $(TARGET_CFINFO) $(TARGET_PCMCIASPEED) $(TARGET_PCMCIACHECK) $(README_NAME).info
	@echo "Generating $(README_NAME) from template..."
	$(eval FULL_SIZE := $(shell stat -c%s $(TARGET_FULL)))
	$(eval FULL_MD5 := $(shell md5sum $(TARGET_FULL) | cut -d' ' -f1))
	$(eval FULL_SHA256 := $(shell sha256sum $(TARGET_FULL) | cut -d' ' -f1))
	$(eval SMALL_SIZE := $(shell stat -c%s $(TARGET_SMALL)))
	$(eval SMALL_MD5 := $(shell md5sum $(TARGET_SMALL) | cut -d' ' -f1))
	$(eval SMALL_SHA256 := $(shell sha256sum $(TARGET_SMALL) | cut -d' ' -f1))
	$(eval CFINFO_SIZE := $(shell stat -c%s $(TARGET_CFINFO)))
	$(eval CFINFO_MD5 := $(shell md5sum $(TARGET_CFINFO) | cut -d' ' -f1))
	$(eval CFINFO_SHA256 := $(shell sha256sum $(TARGET_CFINFO) | cut -d' ' -f1))
	$(eval PCMCIASPEED_SIZE := $(shell stat -c%s $(TARGET_PCMCIASPEED)))
	$(eval PCMCIASPEED_MD5 := $(shell md5sum $(TARGET_PCMCIASPEED) | cut -d' ' -f1))
	$(eval PCMCIASPEED_SHA256 := $(shell sha256sum $(TARGET_PCMCIASPEED) | cut -d' ' -f1))
	$(eval PCMCIACHECK_SIZE := $(shell stat -c%s $(TARGET_PCMCIACHECK)))
	$(eval PCMCIACHECK_MD5 := $(shell md5sum $(TARGET_PCMCIACHECK) | cut -d' ' -f1))
	$(eval PCMCIACHECK_SHA256 := $(shell sha256sum $(TARGET_PCMCIACHECK) | cut -d' ' -f1))
	@sed -e 's|@VERSION@|$(VERSION)|g' \
		 -e 's|@DATE@|$(DATE)|g' \
		 -e 's|@DATE_SHORT@|$(DATE_SHORT)|g' \
		 -e 's|@FULL_SIZE@|$(FULL_SIZE)|g' \
		 -e 's|@FULL_MD5@|$(FULL_MD5)|g' \
		 -e 's|@FULL_SHA256@|$(FULL_SHA256)|g' \
		 -e 's|@SMALL_SIZE@|$(SMALL_SIZE)|g' \
		 -e 's|@SMALL_MD5@|$(SMALL_MD5)|g' \
		 -e 's|@SMALL_SHA256@|$(SMALL_SHA256)|g' \
		 -e 's|@CFINFO_SIZE@|$(CFINFO_SIZE)|g' \
		 -e 's|@CFINFO_MD5@|$(CFINFO_MD5)|g' \
		 -e 's|@CFINFO_SHA256@|$(CFINFO_SHA256)|g' \
		 -e 's|@PCMCIASPEED_SIZE@|$(PCMCIASPEED_SIZE)|g' \
		 -e 's|@PCMCIASPEED_MD5@|$(PCMCIASPEED_MD5)|g' \
		 -e 's|@PCMCIASPEED_SHA256@|$(PCMCIASPEED_SHA256)|g' \
		 -e 's|@PCMCIACHECK_SIZE@|$(PCMCIACHECK_SIZE)|g' \
		 -e 's|@PCMCIACHECK_MD5@|$(PCMCIACHECK_MD5)|g' \
		 -e 's|@PCMCIACHECK_SHA256@|$(PCMCIACHECK_SHA256)|g' \
		 $(README_TEMPLATE) > $@
	@echo "Generated: $@"

# Generate readme only
readme: $(README_NAME) $(README_NAME).info

# Create Aminet-compatible LHA release
release: version-readme $(TARGET_FULL) $(TARGET_SMALL) $(README_NAME) $(README_NAME).info guides check-lha
	@echo "Creating Aminet release: $(ARCHIVE_NAME)"
	@echo "=================================="
	$(eval STAGING := $(shell mktemp -d))
	@mkdir -p "$(STAGING)/cfd/c"
	@mkdir -p "$(STAGING)/cfd/devs"
	@mkdir -p "$(STAGING)/cfd/src"
	@echo "Copying files..."
	@# Binaries
	@cp c/pcmciacheck "$(STAGING)/cfd/c/"
	@cp c/pcmciaspeed "$(STAGING)/cfd/c/"
	@cp c/CFInfo "$(STAGING)/cfd/c/"
	@# Device variants and mountlist
	@cp $(TARGET_FULL) "$(STAGING)/cfd/devs/"
	@cp $(TARGET_SMALL) "$(STAGING)/cfd/devs/"
	@cp devs/CF0 "$(STAGING)/cfd/devs/"
	@cp devs/CF0.info "$(STAGING)/cfd/devs/"
	@# Source code
	@cp src/*.* "$(STAGING)/cfd/src/"
	@# Documentation
	@cp $(README_NAME) "$(STAGING)/cfd/"
	@cp LICENSE "$(STAGING)/cfd/"
	@mkdir -p "$(STAGING)/cfd/docs"
	@cp docs/*.guide "$(STAGING)/cfd/docs/"
	@# Images (optional)
	@mkdir -p "$(STAGING)/cfd/images"
	@cp images/cf-pcmcia-adapter.jpg "$(STAGING)/cfd/images/"
	@cp images/sd-cf-adapter.jpg "$(STAGING)/cfd/images/"
	@cp images/multimode-issue.jpg "$(STAGING)/cfd/images/"
	@# Amiga icon files
	@cp cfd.info "$(STAGING)/"
	@cp c.info "$(STAGING)/cfd/"
	@cp devs.info "$(STAGING)/cfd/"
	@cp images.info "$(STAGING)/cfd/images.info"
	@cp docs.info "$(STAGING)/cfd/"
	@cp LICENSE.info "$(STAGING)/cfd/"
	@cp src.info "$(STAGING)/cfd/"
	@cp $(README_NAME).info "$(STAGING)/cfd/"
	@cp images/cf-pcmcia-adapter.jpg.info "$(STAGING)/cfd/images/"
	@cp images/sd-cf-adapter.jpg.info "$(STAGING)/cfd/images/"
	@cp images/multimode-issue.jpg.info "$(STAGING)/cfd/images/"
	@cp def_CF0.info "$(STAGING)/cfd/"
	@echo "Creating LHA archive..."
	@cd "$(STAGING)" && $(LHA) c "$(ARCHIVE_NAME)" cfd cfd.info
	@mv "$(STAGING)/$(ARCHIVE_NAME)" .
	@rm -rf "$(STAGING)"
	@echo ""
	@echo "=================================="
	@echo "Created: $(ARCHIVE_NAME)"
	@ls -lh "$(ARCHIVE_NAME)"
	@echo ""
	@echo "Contents:"
	@$(LHA) l "$(ARCHIVE_NAME)"
	@echo ""
	@echo "For Aminet upload:"
	@echo "  1. $(ARCHIVE_NAME)"
	@echo "  2. $(README_NAME)"
	@echo ""
	@echo "Upload to: ftp://main.aminet.net/new"

# Check if lha is installed
check-lha:
	@command -v $(LHA) >/dev/null 2>&1 || { \
		echo "ERROR: lha command not found!"; \
		echo "Install with: sudo dnf install lha"; \
		exit 1; \
	}

# ============================================================
# Utility targets
# ============================================================

# Show checksums for both versions
checksums: $(TARGET_FULL) $(TARGET_SMALL) $(TARGET_CFINFO) $(TARGET_PCMCIASPEED) $(TARGET_PCMCIACHECK)
	@for target in $(TARGET_FULL) $(TARGET_SMALL) $(TARGET_CFINFO) $(TARGET_PCMCIASPEED) $(TARGET_PCMCIACHECK); do \
		if [ -f "$$target" ]; then \
			echo "=== $${target} ==="; \
			ls -l "$$target"; \
			echo "MD5:    $$(md5sum "$$target" | cut -d' ' -f1)"; \
			echo "SHA256: $$(sha256sum "$$target" | cut -d' ' -f1)"; \
			echo ""; \
		fi \
	done


# Clean build artifacts
clean:
	rm -f $(TARGET_FULL) $(TARGET_SMALL) $(TARGET_CFINFO) $(TARGET_PCMCIASPEED) $(TARGET_PCMCIACHECK) $(VERSION_INC) $(VERSION_STAMP)

# Clean everything including release archives
distclean: clean
	rm -f cfd*.lha cfd*.readme cfd*.readme.info

# Show help
help:
	@echo "Usage: make [V=1] [target]"
	@echo ""
	@echo "Build targets:"
	@echo "  all    - Build driver + tools (default)"
	@echo "  full   - Build full driver version only (with serial debug capability)"
	@echo "  small  - Build small driver version only (no serial debug code)"
	@echo "  tools  - Build all tools"
	@echo "  guides - Generate AmigaGuide documentation from Markdown"
	@echo ""
	@echo "Options:"
	@echo "  V=1                 - Verbose output (show full compiler messages)"
	@echo "  FASTPIO=1           - Enable Gayle timing optimization (experimental)"
	@echo "  COPYBURST=1         - Enable MOVEM burst transfers (experimental)"
	@echo "  VASM_HOME=/opt/vbcc - vasm installation path"
	@echo "  VBCC_HOME=/opt/vbcc - vbcc installation path"
	@echo ""
	@echo "Release targets:"
	@echo "  version-readme - Update version suffix in README.md (in-place)"
	@echo "  readme         - Generate $(README_NAME) from template"
	@echo "  release        - Create Aminet LHA archive + readme"
	@echo ""
	@echo "Utility targets:"
	@echo "  checksums - Show file sizes and checksums"
	@echo "  clean     - Remove built device files"
	@echo "  distclean - Remove all generated files including archives"
	@echo "  help      - Show this help"
	@echo ""
	@echo "Output files:"
	@echo "  $(TARGET_FULL)- full version (with serial debug capability)"
	@echo "  $(TARGET_SMALL) - small version"
	@echo "  $(TARGET_CFINFO) - card info utility"
	@echo "  $(TARGET_PCMCIASPEED) - pcmcia speed/timing benchmark utility"
	@echo "  $(TARGET_PCMCIACHECK) - pcmcia check utility"
	@echo "  $(README_NAME) - Aminet readme"
	@echo "  $(ARCHIVE_NAME) - Aminet release archive"
	@echo ""
	@echo "Version: $(VERSION) ($(DATE))"

.PHONY: all full small tools guides version-readme readme release check-lha checksums clean distclean help
