; Auto-generated by Makefile
FILE_VERSION	= 1
FILE_REVISION	= 43
VERSION_STRING	macro
	ifd	__68020__
	dc.b	"compactflash.device 1.43-dev (18.05.2026) [68020]"
	else
	dc.b	"compactflash.device 1.43-dev (18.05.2026) [68000]"
	endc
	endm
