; Auto-generated by Makefile
FILE_VERSION	= 1
FILE_REVISION	= 41
VERSION_STRING	macro
	ifd	__68020__
	dc.b	"compactflash.device 1.41-dev (18.04.2026) [68020]"
	else
	dc.b	"compactflash.device 1.41-dev (18.04.2026) [68000]"
	endc
	endm
